---
title: 'Lab 3: Instructions'
author: "Jeremy Morris"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Objectives

* Learn the basics of using the ggplot function
* Go from data acquisition to visualization

### Instructions

* Review the in-class lab found in this project.
* Find a data set you think interesting.
* Create a single interesting plot using ggplot which includes:
    * Data with mapping to aesthetics beyond x and y (i.e. color, fill, alpha)
    * At least one of the following.
        * Scale
        * Label
        * Coordinate
    * A facet specification
* Write a short description explaining what you have done and why it is interesting.
* Upload the HTML file to Canvas.

### Notes on the assignment requirements

* This assignment requires exactly one visualization. You will lose 50% of remaining points for each additional visualization included. As an example, an assignment with two visualizations will be eligible for 50% of the points. An assignment with three will have a max score of 25% of the available points.
* Assignments that do not use `ggplot` will recieve 0 points.
* 2 point will be deducted for each ggplot sub-function not used.
* 1 point will be deducted if your explination of the plot does not match what the plot represents.
* 0 points will be awarded for answers not using R Markdown.
* 2 points will be deducted if you do not put your name on the final product.

### Work locally
If you would prefer to work locally, you can fork the following repository from my GitHub account. Note that I will not be able to see your assignment if you work this way. Go to the following url and fork the repo if you would like to work locally.

https://github.com/jeremydmorris/lab_3_ggplot